spring:
  application:
    name: mscartoes

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://10.0.0.105:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring-cloud.application.instance_id:${random.value}}
